Add slb and Attach ecs to slb.
alibabacloud-automation/terraform-alicloud-market-wordpress pull request #2
Opened 2020-02-13 09:29 UTC by lixue323

2020-02-13 09:47 UTC, Rich-yi commented on examples/complete/main.tf
>    image_id                   = "m-2ze69pmuqqu88qn5h47u"
m-2ze69pmuqqu88qn5h47u 去敏感

2020-02-13 09:47 UTC, Rich-yi commented on README-CN.md
>    vswitch_id                 = "vsw-345678"
这也补一下xxx吧

2020-02-13 09:47 UTC, Rich-yi commented on README.md
>    vswitch_id                 = "vsw-345678"
一样

2020-02-13 09:47 UTC, Rich-yi commented on CHANGELOG.md
> +- Add backend servers (ECS instance) to the SLB [GH-2]( https://github.com/terraform-alicloud-modules/terraform-alicloud-market-wordpress/pull/2)
changelog格式得空行

2020-02-13 10:00 UTC, zql-tqy commented on CHANGELOG.md
> +- Add backend servers (ECS instance) to the SLB [GH-2]( https://github.com/terraform-alicloud-modules/terraform-alicloud-market-wordpress/pull/2)
这个change log的模板参考一下https://github.com/terraform-alicloud-modules/terraform-alicloud-rds-mysql/blob/master/CHANGELOG.md

2020-02-13 10:00 UTC, zql-tqy commented on variables.tf
> +  type        = string
确定一下有没有默认值

2020-02-13 10:00 UTC, zql-tqy commented on main.tf
> +    port       = 80
这个是写死的么？

2020-02-13 10:00 UTC, zql-tqy commented on main.tf
> +  address_type      = "internet"
确认一下参数是不是固定的

2020-02-13 10:05 UTC, lixue323 commented on examples/complete/main.tf
>    image_id                   = "m-2ze69pmuqqu88qn5h47u"
这个是云市场公开的image, 还用去吗？

2020-02-14 04:37 UTC, xiaozhu36 requested changes

2020-02-14 04:37 UTC, xiaozhu36 commented on main.tf
> +  name              = var.slb_name
这个地方要加一个开关，create_slb

2020-02-14 04:37 UTC, xiaozhu36 commented on main.tf
> +  create = var.domain_name != "" ? 1 : 0
这个开关要改成 bind_domain，如果为true，与dns进行绑定

2020-02-14 04:37 UTC, xiaozhu36 commented on outputs.tf
> +output "this_domain_address" {
this_wordpress_url

2020-02-14 04:37 UTC, xiaozhu36 commented on outputs.tf
> +  value       = format("http://%s", alicloud_instance.this.*.public_ip[0])
ip地址就保留ip地址

2020-02-14 06:34 UTC, xiaozhu36 approved these changes

2020-02-14 06:36 UTC, merged